print("Let's play MadLibs for Homework 1")
print('Type one word responses to the following:')
a = input('proper_name ==> ' )
print(a)
b = input('adjective ==> ')
print(b)
c = input('noun ==> ')
print(c)
d = input('verb ==> ')
print(d)
e = input('noun ==> ')
print(e)
f = input('emotion ==> ')
print(f)
g = input('verb ==> ')
print(g)
h = input('noun ==> ')
print(h)
i = input('noun ==> ')
print(i)
j = input('season ==> ')
print(j)
k = input('emotion ==> ')
print(k)
l = input('team-name ==> ')
print(l)
m = input('adjective ==> ')
print(m)

print('\nHere is your Mad Lib...')

print('\nHello',a+',')
print('  Good morning!  Are you looking forward to a/an',b, c+'?')
print('  You will',d, 'a lot of', e, 'and feel',f, 'when you do.')
print('  If you do not, you will', g, 'this', h+'.\n')
print('  Did you watch the', i,'this',j+'?')
print('  Were you', k, 'when the', l, 'won?')
print('  Have a/an', m, 'day!')
